apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gluent-bit-read
subjects:
  - kind: ServiceAccount
    name: gluent-bit
    namespace: logging