apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gluent-bit
  namespace: logging
  labels:
    k8s-app: gluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: gluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - name: gluent-bit
          image: ostretsov/gluent-bit:latest
          imagePullPolicy: Always
          env:
          - name: GRAYLOG_HOST
            value: "graylog.graylog.svc.cluster.local"  # CHANGE IF DIFFERENT !
          - name: GRAYLOG_PORT
            value: "12201"                              # CHANGE IF DIFFERENT !
          - name: DEBUG                                 # UNCOMMENT IF THERE ARE PROBLEMS
            value: "true"
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      terminationGracePeriodSeconds: 10
      serviceAccountName: gluent-bit
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "NoSchedule"